### ISSUE TITLE
Gérer les norloges lointaines

### ISSUE THREAD

**Issue by devnewton** [devnewton/gb3#1]
Loin comment?

**Comment by gle42** [comment]
Voir comment fait jb3 qui gère ça correctement.

Il peut y avoir une règle du type "Le contenu référencé par une horloge distante de plus de N posts du post le plus récent du backend s'affiche en popup quand on la survole" avec N de l'ordre de 25 ou 30 (peut-être moins sur mobile, peut-être faut-il faire varier N dynamiquement selon la dimension verticale de l'écran ?)

**Comment by devnewton** [comment]
C'est fée !
